// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBI_RMvj3JEW1M4qOIW9fF6mRnXjXs5i94',
    appId: '1:522334842203:web:20e6bdfcd933ffbf297e7e',
    messagingSenderId: '522334842203',
    projectId: 'globroker',
    authDomain: 'globroker.firebaseapp.com',
    storageBucket: 'globroker.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdmGCWPX5oPulSYyFJfD3xGnOhmTWRBhA',
    appId: '1:522334842203:android:753357ae13c7bb70297e7e',
    messagingSenderId: '522334842203',
    projectId: 'globroker',
    storageBucket: 'globroker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPq2M1UJTbVT44YdhB5-aWpk3EeHbNVOM',
    appId: '1:522334842203:ios:be99577ae924bee0297e7e',
    messagingSenderId: '522334842203',
    projectId: 'globroker',
    storageBucket: 'globroker.firebasestorage.app',
    iosBundleId: 'com.hasanshukurov.globroker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPq2M1UJTbVT44YdhB5-aWpk3EeHbNVOM',
    appId: '1:522334842203:ios:442bc03b2f53995e297e7e',
    messagingSenderId: '522334842203',
    projectId: 'globroker',
    storageBucket: 'globroker.firebasestorage.app',
    iosBundleId: 'com.hasanshukurov.globroker.globroker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBI_RMvj3JEW1M4qOIW9fF6mRnXjXs5i94',
    appId: '1:522334842203:web:aeccd5774c767127297e7e',
    messagingSenderId: '522334842203',
    projectId: 'globroker',
    authDomain: 'globroker.firebaseapp.com',
    storageBucket: 'globroker.firebasestorage.app',
  );
}
